### ISSUE TITLE
Support other plantUML servers

### ISSUE THREAD

**Issue by ashaw93** [KyleKorndoerfer/BracketsUML#14]
Could the ability to enter another server than the plantUML service be added?

**Comment by KyleKorndoerfer** [comment]
Sure. I'll just need to read-up on adding preferences to extensions. I would want to make sure that when the extension is installed it would set the default PlantUML service url instead of hardcoding the value into the code.

**Comment by KyleKorndoerfer** [comment]
There is now a preference that gets added to your local preference file called **bracketsuml.plantUMLServiceUrl** that will hold the address of the PlantUML service that you would like to use (defaults to the PlantUML.com service)
